robot:
  type: ur5_hdd
  robot_ip: "192.168.0.102"
  gripper_port: "/dev/ttyUSB0"
  gripper_baudrate: 115200
  gripper_slave_id: 1
  move_speed: 0.5
  move_acceleration: 0.5
  ee_speed: 0.05
  ee_acceleration: 0.05
  ee_step_size: 0.005
  gripper_step_size: 1
  cameras:
    top:
      type: intelrealsense
      serial_number_or_name: "333422305051"
      width: 640
      height: 480
      fps: 5
      warmup_s: 3
    side_left:
      type: intelrealsense
      serial_number_or_name: "333422303023"
      width: 640
      height: 480
      fps: 5
      warmup_s: 3
    side_right:
      type: intelrealsense
      serial_number_or_name: "338122302446"
      width: 640
      height: 480
      fps: 5
      warmup_s: 3

teleop:
  type: keyboard_ee

dataset:
  repo_id: "toyoshima/ur5_ab_grip_test"
  root: "/mnt/data/lerobot_datasets_ab_grip"
  single_task: "Move arm from 0 to A to B, close gripper at B, move to C, open gripper at C, return to 0"
  fps: 5
  episode_time_s: 50   # extra time for 3-4s dwell at C before and after opening gripper
  reset_time_s: 10
  num_episodes: 20
  video: true
  push_to_hub: false
  streaming_encoding: true
  encoder_threads: 4
  vcodec: "auto"

display_data: false
